### ISSUE TITLE
Player pathfinding restart

### ISSUE THREAD

**Issue by Jon-Francis** [ccondie/SurviveTheNight#2]
If a player is walking a calculated path and a zombie traps him by getting in his way, the player returns to his starting point by walking through walls in a straight line.

**Comment by amanwaring** [comment]
I know exactly what's causing this

**Comment by amanwaring** [comment]
@Jon-Francis do you want to test this again and see if it's fixed?

**Comment by Jon-Francis** [comment]
I have not been able to duplicate it so I believe it is fixed
