### ISSUE TITLE
Player/enemy movement animations stop working over time

### ISSUE THREAD

**Issue by amanwaring** [ccondie/SurviveTheNight#4]
The player seems to always point the right direction when he's moving, but the animation of him walking (moving his feet) don't always work. It seems like the movement animation stops working after the player collides with a zombie mid path (but I haven't nailed down exactly what causes this).

**Comment by Jon-Francis** [comment]
Does this still happen after the last shooting animation update? I basically told it to check continuously if the place is moving but not walking and then play the walking animation if so.

**Comment by amanwaring** [comment]
That does seem to have fixed it for the player, could you make the same change for the zombies?

**Comment by Jon-Francis** [comment]
I'll look into it but the behavior is a little different because the zombies never stop walking, they just change directions.

**Comment by Jon-Francis** [comment]
I changed a few things but there are still some issues with zombies changing direction once they have caught up to the player.
